import { Product, Branch, Faq } from '@/types';

export const mockSavingsProducts: Product[] = [
  {
    id: '1',
    type: 'savings',
    name: 'Cuenta Vista',
    slug: 'cuenta-vista',
    shortDescription: 'Tu cuenta de ahorros con acceso inmediato a tus fondos. Disponibilidad total y seguridad.',
    longDescription: 'La Cuenta Vista es el producto base de la cooperativa. Te permite realizar depósitos y retiros en cualquier momento, acceder a servicios digitales, recibir transferencias y pagos, y ser parte de la familia cooperativista.',
    benefits: ['Acceso inmediato a tus fondos', 'Sin costo de mantenimiento', 'Tarjeta de débito incluida', 'Acceso a banca virtual y app móvil', 'Intereses competitivos sobre saldo', 'Seguro de depósitos COSEDE'],
    requirements: ['Cédula de identidad vigente', 'Planilla de servicio básico actualizada', 'Depósito mínimo de apertura: $25', 'Formulario de vinculación'],
    referenceRate: 2.0,
    minAmount: 25,
    ctaLabel: 'Abrir mi cuenta',
    iconName: 'Wallet',
    isFeatured: true,
    sortOrder: 1,
  },
  {
    id: '2',
    type: 'savings',
    name: 'Ahorro Programado',
    slug: 'ahorro-programado',
    shortDescription: 'Ahorra de forma disciplinada con aportes mensuales fijos y alcanza tus metas.',
    longDescription: 'El Ahorro Programado te ayuda a construir el hábito del ahorro con un plan personalizado. Defines tu meta, plazo y aporte mensual, y nosotros te acompañamos hasta cumplirla.',
    benefits: ['Tasa preferencial de ahorro', 'Plazo y monto flexible', 'Débito automático opcional', 'Seguimiento de meta en app', 'Sin penalidad por aportes extra'],
    requirements: ['Ser socio activo con Cuenta Vista', 'Aporte mínimo mensual: $20', 'Plazo mínimo: 6 meses'],
    referenceRate: 5.5,
    minAmount: 20,
    ctaLabel: 'Empezar a ahorrar',
    iconName: 'PiggyBank',
    isFeatured: true,
    sortOrder: 2,
  },
  {
    id: '3',
    type: 'savings',
    name: 'Ahorro Infantil "Semillitas"',
    slug: 'ahorro-infantil-semillitas',
    shortDescription: 'Siembra hoy el futuro de los más pequeños con una cuenta pensada para ellos.',
    longDescription: 'Semillitas es nuestra cuenta de ahorro infantil diseñada para fomentar la cultura del ahorro desde temprana edad.',
    benefits: ['Tasa preferencial infantil', 'Actividades educativas de ahorro', 'Material didáctico incluido', 'Seguro de vida para el titular', 'Incentivos por ahorro sostenido'],
    requirements: ['Cédula del representante legal', 'Partida de nacimiento del menor', 'Depósito mínimo: $10'],
    referenceRate: 4.0,
    minAmount: 10,
    ctaLabel: 'Abrir Semillitas',
    iconName: 'Baby',
    isFeatured: false,
    sortOrder: 3,
  },
  {
    id: '4',
    type: 'savings',
    name: 'Depósito a Plazo Fijo',
    slug: 'deposito-plazo-fijo',
    shortDescription: 'Invierte tu dinero a plazo fijo y obtén los mejores rendimientos del mercado.',
    longDescription: 'El Depósito a Plazo Fijo es la opción ideal para quienes buscan rentabilidad segura. Elige el monto y el plazo, y nosotros te garantizamos una tasa fija.',
    benefits: ['Tasas superiores al promedio', 'Plazos desde 30 a 360 días', 'Certificado negociable', 'Intereses mensuales o al vencimiento', 'Garantía COSEDE hasta $32,000', 'Renovación automática'],
    requirements: ['Ser socio activo', 'Monto mínimo: $500', 'Documento de identidad'],
    referenceRate: 8.5,
    minAmount: 500,
    maxAmount: 500000,
    minTerm: 1,
    maxTerm: 12,
    ctaLabel: 'Invertir ahora',
    iconName: 'TrendingUp',
    isFeatured: true,
    sortOrder: 4,
  },
];

export const mockCreditProducts: Product[] = [
  {
    id: '5',
    type: 'credit',
    name: 'Crédito de Consumo',
    slug: 'credito-consumo',
    shortDescription: 'Financia tus proyectos personales con cuotas cómodas y aprobación rápida.',
    longDescription: 'Nuestro crédito de consumo está diseñado para que puedas cumplir tus metas personales: viajes, electrodomésticos, salud, educación o cualquier necesidad.',
    benefits: ['Aprobación en 48 horas', 'Sin garante hasta $5,000', 'Plazos hasta 60 meses', 'Seguro de desgravamen incluido', 'Pago mediante débito automático'],
    requirements: ['Ser socio activo mínimo 3 meses', 'Cédula y papeleta de votación', 'Justificación de ingresos', 'Planilla de servicio básico', 'Referencias personales'],
    referenceRate: 15.5,
    minAmount: 500,
    maxAmount: 30000,
    minTerm: 3,
    maxTerm: 60,
    ctaLabel: 'Solicitar crédito',
    iconName: 'CreditCard',
    isFeatured: true,
    sortOrder: 1,
  },
  {
    id: '6',
    type: 'credit',
    name: 'Microcrédito',
    slug: 'microcredito',
    shortDescription: 'Capital de trabajo para impulsar tu negocio o emprendimiento.',
    longDescription: 'El microcrédito está orientado a emprendedores, comerciantes y pequeños productores que necesitan capital de trabajo.',
    benefits: ['Evaluación simplificada', 'Visita de campo incluida', 'Asesoría para tu negocio', 'Plazos adaptados a tu flujo', 'Períodos de gracia'],
    requirements: ['Actividad económica mínimo 6 meses', 'Cédula de identidad', 'RUC o RISE', 'Justificación de ingresos', 'Planilla de servicio básico'],
    referenceRate: 20.5,
    minAmount: 200,
    maxAmount: 20000,
    minTerm: 3,
    maxTerm: 48,
    ctaLabel: 'Impulsar mi negocio',
    iconName: 'Store',
    isFeatured: true,
    sortOrder: 2,
  },
  {
    id: '7',
    type: 'credit',
    name: 'Crédito de Vivienda',
    slug: 'credito-vivienda',
    shortDescription: 'Construye, compra o mejora tu hogar con las mejores condiciones.',
    longDescription: 'Haz realidad el sueño de la casa propia con nuestro crédito de vivienda. Financiamos hasta el 80% del avalúo.',
    benefits: ['Financiamiento hasta 80% del avalúo', 'Plazos hasta 20 años', 'Tasa regulada por SEPS', 'Seguro de desgravamen', 'Seguro contra incendio', 'Pre-aprobación en 5 días'],
    requirements: ['Socio activo mínimo 6 meses', 'Ingresos familiares comprobables', 'Avalúo del inmueble', 'Certificado de gravámenes', 'Aporte mínimo del 20%'],
    referenceRate: 10.75,
    minAmount: 10000,
    maxAmount: 150000,
    minTerm: 12,
    maxTerm: 240,
    ctaLabel: 'Tu casa propia',
    iconName: 'Home',
    isFeatured: true,
    sortOrder: 3,
  },
];

export const mockBranches: Branch[] = [
  {
    id: '1',
    name: 'Agencia Centro Histórico (Principal)',
    city: 'Cuenca',
    address: 'Bolívar 7-89 y Borrero, Centro Histórico',
    phone: '(07) 283-4567',
    schedule: [{ day: 'Lunes a Viernes', hours: '8:30 - 17:30' }, { day: 'Sábados', hours: '9:00 - 13:00' }],
    lat: -2.8974,
    lng: -79.0045,
    isMain: true,
  },
  {
    id: '2',
    name: 'Agencia El Vergel',
    city: 'Cuenca',
    address: 'Av. Fray Vicente Solano 4-28 y Florencia Astudillo',
    phone: '(07) 283-4570',
    schedule: [{ day: 'Lunes a Viernes', hours: '8:30 - 17:00' }, { day: 'Sábados', hours: '9:00 - 13:00' }],
    lat: -2.9037,
    lng: -79.0128,
    isMain: false,
  },
  {
    id: '3',
    name: 'Agencia Totoracocha',
    city: 'Cuenca',
    address: 'Av. González Suárez y Calle del Retorno',
    phone: '(07) 283-4573',
    schedule: [{ day: 'Lunes a Viernes', hours: '8:30 - 17:00' }, { day: 'Sábados', hours: '9:00 - 13:00' }],
    lat: -2.8912,
    lng: -78.9893,
    isMain: false,
  },
  {
    id: '4',
    name: 'Agencia Yanuncay',
    city: 'Cuenca',
    address: 'Av. Loja y Calle Imbabura, sector Yanuncay',
    phone: '(07) 283-4576',
    schedule: [{ day: 'Lunes a Viernes', hours: '8:30 - 17:00' }, { day: 'Sábados', hours: '9:00 - 12:00' }],
    lat: -2.9156,
    lng: -79.017,
    isMain: false,
  },
  {
    id: '5',
    name: 'Agencia Monay',
    city: 'Cuenca',
    address: 'Av. 24 de Mayo, Monay Shopping, local 15',
    phone: '(07) 283-4579',
    schedule: [{ day: 'Lunes a Viernes', hours: '9:00 - 19:00' }, { day: 'Sábados', hours: '9:00 - 17:00' }, { day: 'Domingos', hours: '10:00 - 14:00' }],
    lat: -2.9234,
    lng: -78.9812,
    isMain: false,
  },
];

export const mockFaqs: Faq[] = [
  { id: '1', category: 'Cuentas', question: '¿Cómo abro una cuenta en la cooperativa?', answer: 'Para abrir tu cuenta necesitas acercarte a cualquiera de nuestras agencias con tu cédula de identidad vigente, una planilla de servicio básico y el depósito mínimo de $25.', sortOrder: 1 },
  { id: '2', category: 'Cuentas', question: '¿Cuál es el depósito mínimo?', answer: 'El depósito mínimo de apertura es de $25 para Cuenta Vista y $10 para Semillitas.', sortOrder: 2 },
  { id: '3', category: 'Créditos', question: '¿Cuáles son los requisitos para un crédito?', answer: 'Los requisitos básicos son: ser socio activo, cédula de identidad, justificación de ingresos, planilla de servicio básico y referencias personales.', sortOrder: 1 },
  { id: '4', category: 'Créditos', question: '¿Cuánto tarda la aprobación?', answer: 'Créditos de consumo hasta $5,000 se aprueban en 48 horas. Montos mayores entre 5 y 10 días hábiles.', sortOrder: 2 },
  { id: '5', category: 'Créditos', question: '¿Puedo pagar anticipadamente?', answer: 'Sí, puedes realizar pagos anticipados sin penalización. Reduce capital e intereses futuros.', sortOrder: 3 },
  { id: '6', category: 'Servicios Digitales', question: '¿Cómo accedo a la banca virtual?', answer: 'Regístrate en cualquier agencia con tu cédula. Recibirás usuario y contraseña temporal.', sortOrder: 1 },
  { id: '7', category: 'Seguridad', question: '¿Mi dinero está seguro?', answer: 'Sí. Estamos regulados por la SEPS y tus depósitos están protegidos por COSEDE hasta $32,000.', sortOrder: 1 },
  { id: '8', category: 'General', question: '¿Qué horario de atención tienen?', answer: 'Lunes a Viernes 8:30-17:00, Sábados 9:00-13:00. Monay Shopping tiene horario extendido.', sortOrder: 1 },
];
